### ISSUE TITLE
Update to Nuke 11

### ISSUE THREAD

**Issue by Digifais** [RynBelz162/Xamarin.Moab#1]
@RynBelz162 Is it possible for you to update this binding library to the latest version of Nuke 11?

**Comment by RynBelz162** [comment]
Hello,

I have gone ahead and updated to version 11.6.4 of Nuke for the Framework Proxy. However a few points I would like to make it known:

1. I did not add any new functionality that was in the newer versions. I just updated existing swift code to work with the newer API of Nuke 11.6.4.
2. I would implore you to read the updated version of the README to see some warnings I have added when consuming this nuget package going forward.
3. TLDR I really only test the library very very quickly to make sure it just loads images now.
